(function($){$.fn.jFlow=function(options){var opts=$.extend({},$.fn.jFlow.defaults,options);var randNum=Math.floor(Math.random()*11);var jFC=opts.controller;var jFS=opts.slideWrapper;var jSel=opts.selectedWrapper;var cur=0;var timer;var maxi=$(jFC).length;var width=$(opts.slides).children().outerWidth();var slidesNum=$(opts.slides).children().size();var totalWidth=width*slidesNum;var lastSlide=(slidesNum-1);var additionalSlide=slidesNum+1;var pause=opts.pause;var slide=function(dur,i){$(opts.slides).children().css({overflow:"hidden"});$(opts.slides+" iframe").hide().addClass("temp_hide");if(opts.effect=="rewind"){$(opts.slides).animate({marginLeft:"-"+(i*$(opts.slides).find(":first-child").width()+"px")},opts.duration*(dur),opts.easing,function(){$(opts.slides).children().css({overflow:"hidden"});$(".temp_hide").show();});}
else if(opts.effect=="flow"){if(i!=0){$("#mySlides").animate({left:-(i*width)},function(){if((slidesNum-1)==i){$(".jFlowSlideContainer").first().css({left:(width*slidesNum)});}});movePagingClass();}
else{$(".jFlowSlideContainer").first().animate({left:(width*slidesNum)});$(opts.slides).css({width:(width*additionalSlide)});$(opts.slides).animate({left:"-"+totalWidth},function(){$(this).css('left','0px');$(".jFlowSlideContainer").first().css('left','0px');});$('.jFlowSelected').removeClass('jFlowSelected');$(jFC).first().addClass('jFlowSelected');}}}
var movePagingClass=function(){var thisController=$('.jFlowSelected');$(thisController).removeClass('jFlowSelected');$(thisController).next().addClass('jFlowSelected');}
$(this).find(jFC).each(function(i){$(jFC).first().click(function(){$('.jFlowSlideContainer').first().css({left:'0px'});$('#mySlides').animate({left:'0px'});$(jFC).removeClass(jSel);$(this).addClass(jSel);});$(this).click(function(){dotimer();if($(opts.slides).is(":not(:animated)")){var dur=Math.abs(cur-i);slide(dur,i);cur=i;$(jFC).removeClass(jSel);$(this).addClass(jSel);}});});$(opts.slides).before('<div id="'+jFS.substring(1,jFS.length)+'"></div>').appendTo(jFS);$(opts.slides).find(".slide").each(function(){$(this).before('<div class="jFlowSlideContainer"></div>').appendTo($(this).prev());});$(jFC).eq(cur).addClass(jSel);var resize=function(x){$(jFS).css({position:"relative",width:opts.width,height:opts.height,overflow:"hidden"});$(opts.slides).css({position:"relative",width:$(jFS).width()*$(jFC).length+"px",height:$(jFS).height()+"px",overflow:"hidden"});$(opts.slides).children().css({position:"relative",width:$(jFS).width()+"px",height:$(jFS).height()+"px","float":"left",overflow:"hidden"});$(opts.slides).css({marginLeft:"-"+(cur*$(opts.slides).find(":eq(0)").width()+"px")});}
resize();$(window).resize(function(){resize();});$(opts.prev).click(function(){dotimer();doprev();});$(opts.next).click(function(){dotimer();donext();});var doprev=function(x){if(opts.effect=='rewind'){if($(opts.slides).is(":not(:animated)")){var dur=1;if(cur>0){cur--;}else{cur=maxi-1;dur=cur;}
$(jFC).removeClass(jSel);slide(dur,cur);$(jFC).eq(cur).addClass(jSel);}}
else if(opts.effect=='flow'){if(cur==0){$(opts.slides).css({width:(width*additionalSlide)});$('.jFlowSlideContainer:last').css({position:"absolute",left:"-"+width+"px"});$('#mySlides').animate({paddingLeft:width+"px"});$('.jFlowSlideContainer:last').animate({left:"0px"},function(){$(this).css({position:"relative",left:""});$('#mySlides').css({padding:"0px",left:"-"+(totalWidth-width)+"px"});});cur=slidesNum-1;$('.jFlowSelected').removeClass('jFlowSelected');$(jFC).last().addClass('jFlowSelected');}
else{if($(opts.slides).find(":first-child").css({left:totalWidth})){$(opts.slides).find(":first-child").css('left','0px');}
$('#mySlides').animate({left:-(width*(cur-1))},{queue:false});cur=cur-1;var thisController=$('.jFlowSelected');$(thisController).removeClass('jFlowSelected');$(thisController).prev().addClass('jFlowSelected');}}else{alert('Error: No effect entered as option!');}}
var donext=function(x){if(cur==lastSlide){$(".jFlowSlideContainer").first().css({"left":totalWidth+"px"});}
if(opts.effect=='rewind'){if($(opts.slides).is(":not(:animated)")){var dur=1;if(cur<maxi-1)cur++;else{cur=0;dur=maxi-1;}
$(jFC).removeClass(jSel);slide(dur,cur);$(jFC).eq(cur).addClass(jSel);}}
else if(opts.effect=='flow'){if($(opts.slides).is(":not(:animated)")){var dur=1;if(cur<maxi-1)cur++;else{cur=0;dur=maxi-1;}}
slide(dur,cur);}}
var dotimer=function(x){if((opts.auto)==true){if(timer!=null)clearInterval(timer);timer=setInterval(function(){$(opts.next).click();},pause);}}
dotimer();$(opts.slides).hover(function(){clearInterval(timer);},function(){dotimer();});};$.fn.jFlow.defaults={controller:".jFlowControl",slideWrapper:"#jFlowSlider",slides:"#mySlides",selectedWrapper:"jFlowSelected",effect:"flow",width:"800px",height:"350px",duration:400,pause:5000,prev:".jFlowPrev",next:".jFlowNext",auto:true};})(jQuery);